name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to DockerHub
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Build and Push the Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t sandydevopsstuffs/flask-app:$GITHUB_SHA .
        docker tag sandydevopsstuffs/flask-app:$GITHUB_SHA sandydevopsstuffs/flask-app:latest
        docker push sandydevopsstuffs/flask-app:$GITHUB_SHA
        docker push sandydevopsstuffs/flask-app:latest

    # Configure AWS CLI
    - name: Configure AWS CLI
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name devops-cluster

    # Deploy to Kubernetes
    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/flask-app flask-app=sandydevopsstuffs/flask-app:latest
        kubectl rollout status deployment/flask-app
